import React, { useState, useEffect } from 'react';
import PredictionCard from '../components/PredictionCard';
import { AlertTriangle, BarChart2 } from 'lucide-react';

const PredictionsPage = () => {
  const [activeTab, setActiveTab] = useState('4d'); // '4d' or 'toto'
  const [loading, setLoading] = useState(false);
  const [predictions, setPredictions] = useState([]);

  // Mock Data for Demo (Replace this with actual fetch call to your API)
  const mockData = {
    '4d': [
      { model_name: 'Statistical Frequency', predicted_numbers: ['0630', '8846', '6485'], confidence_score: 0.55, rationale: 'Identifies "Hot Numbers" based on historical frequency (Law of Large Numbers).' },
      { model_name: 'XGBoost Regressor', predicted_numbers: ['6296', '1120', '4055'], confidence_score: 0.60, rationale: 'Uses Decision Trees to model the relationship between Draw Date and winning numbers.' },
      { model_name: 'LSTM Neural Network', predicted_numbers: ['5124', '9901', '3321'], confidence_score: 0.45, rationale: 'A Neural Network that learns temporal patterns from the sequence of past 1st Prizes.' },
    ],
    'toto': [
      { model_name: 'XGBoost Classifier', predicted_numbers: [5, 12, 23, 34, 40, 45], confidence_score: 0.65, rationale: 'Calculates the individual probability of each ball appearing based on calendar patterns.' },
      { model_name: 'LSTM Sequence', predicted_numbers: [1, 8, 19, 22, 30, 49], confidence_score: 0.42, rationale: 'Recognizes sequential patterns and "momentum" in the winning numbers.' },
    ]
  };

  const handleGenerate = async () => {
    setLoading(true);
    // Simulate API delay
    setTimeout(() => {
      setPredictions(mockData[activeTab]);
      setLoading(false);
    }, 1500);
    
    // REAL CODE:
    // const res = await fetch(`http://localhost:8000/api/predict/${activeTab}`);
    // const data = await res.json();
    // setPredictions(data);
  };

  return (
    <div className="min-h-screen p-4 md:p-8" style={{backgroundColor: '#020617'}}>
      <div className="max-w-6xl mx-auto">
        
        {/* Header Section */}
        <div className="mb-8">
          <h1 className="text-4xl font-bold text-white mb-3">Predictive Analysis</h1>
          <p style={{color: '#cbd5e1'}}>
            AI-powered forecasts using Statistical, Machine Learning, and Deep Learning models.
          </p>
        </div>

        {/* Disclaimer Banner (Compliance Requirement) */}
        <div className="p-4 mb-8 rounded-lg" style={{background: 'rgba(251, 191, 36, 0.1)', border: '1px solid rgba(251, 191, 36, 0.3)', borderLeft: '4px solid #f59e0b'}}>
          <div className="flex items-start">
            <AlertTriangle className="h-5 w-5 mr-3 mt-0.5" style={{color: '#fbbf24'}} />
            <div>
              <h3 className="text-sm font-semibold" style={{color: '#fbbf24'}}>Educational Purpose Only</h3>
              <p className="text-sm mt-1" style={{color: '#cbd5e1'}}>
                These predictions are generated by experimental algorithms. Lottery draws are stochastic processes; 
                past performance does not guarantee future results. Do not use for gambling.
              </p>
            </div>
          </div>
        </div>

        {/* Controls */}
        <div className="flex flex-col sm:flex-row justify-between items-center mb-8 gap-4">
          {/* Game Toggle */}
          <div className="p-1 rounded-lg flex" style={{background: '#0f172a', border: '1px solid #1e293b'}}>
            <button
              onClick={() => { setActiveTab('4d'); setPredictions([]); }}
              className="px-6 py-2 rounded-md text-sm font-medium transition-all"
              style={{
                background: activeTab === '4d' ? 'rgba(59, 130, 246, 0.15)' : 'transparent',
                color: activeTab === '4d' ? '#60a5fa' : '#94a3b8',
                border: activeTab === '4d' ? '1px solid rgba(59, 130, 246, 0.3)' : '1px solid transparent'
              }}
              onMouseEnter={(e) => {
                if (activeTab !== '4d') {
                  e.target.style.color = '#cbd5e1';
                }
              }}
              onMouseLeave={(e) => {
                if (activeTab !== '4d') {
                  e.target.style.color = '#94a3b8';
                }
              }}
            >
              4D
            </button>
            <button
              onClick={() => { setActiveTab('toto'); setPredictions([]); }}
              className="px-6 py-2 rounded-md text-sm font-medium transition-all"
              style={{
                background: activeTab === 'toto' ? 'rgba(124, 58, 237, 0.15)' : 'transparent',
                color: activeTab === 'toto' ? '#a78bfa' : '#94a3b8',
                border: activeTab === 'toto' ? '1px solid rgba(124, 58, 237, 0.3)' : '1px solid transparent'
              }}
              onMouseEnter={(e) => {
                if (activeTab !== 'toto') {
                  e.target.style.color = '#cbd5e1';
                }
              }}
              onMouseLeave={(e) => {
                if (activeTab !== 'toto') {
                  e.target.style.color = '#94a3b8';
                }
              }}
            >
              TOTO
            </button>
          </div>

          {/* Action Button */}
          <button
            onClick={handleGenerate}
            disabled={loading}
            className="flex items-center px-6 py-3 rounded-lg font-semibold text-white transition-all"
            style={{
              background: loading ? '#64748b' : '#7c3aed',
              cursor: loading ? 'not-allowed' : 'pointer',
              boxShadow: loading ? 'none' : '0 0 20px rgba(124, 58, 237, 0.3)'
            }}
            onMouseEnter={(e) => {
              if (!loading) {
                e.target.style.background = '#6d28d9';
                e.target.style.boxShadow = '0 0 30px rgba(124, 58, 237, 0.5)';
              }
            }}
            onMouseLeave={(e) => {
              if (!loading) {
                e.target.style.background = '#7c3aed';
                e.target.style.boxShadow = '0 0 20px rgba(124, 58, 237, 0.3)';
              }
            }}
          >
            {loading ? 'Running Models...' : `Generate ${activeTab.toUpperCase()} Forecast`}
          </button>
        </div>

        {/* Grid Layout for Cards */}
        {predictions.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {predictions.map((pred, index) => (
              <PredictionCard
                key={index}
                type={activeTab}
                modelName={pred.model_name}
                numbers={pred.predicted_numbers}
                confidence={pred.confidence_score}
                rationale={pred.rationale}
              />
            ))}
          </div>
        ) : (
          /* Empty State */
          <div className="text-center py-20 rounded-xl border border-dashed" style={{background: '#0f172a', borderColor: '#334155'}}>
            <div className="mx-auto h-12 w-12 mb-4" style={{color: '#64748b'}}>
              <BarChart2 className="w-full h-full" />
            </div>
            <h3 className="text-lg font-medium text-white">No predictions yet</h3>
            <p className="mt-1" style={{color: '#94a3b8'}}>Select a game and click generate to run the AI models.</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default PredictionsPage;