import React, { useState, useEffect } from 'react';
import PredictionCard from '../components/PredictionCard';
import { AlertTriangle, BarChart2 } from 'lucide-react';
import { getPredictions } from '../services/api';

const PredictionsPage = () => {
  const [activeTab, setActiveTab] = useState('4d'); // '4d' or 'toto'
  const [loading, setLoading] = useState(false);
  const [predictions, setPredictions] = useState([]);
  const [error, setError] = useState(null);
  const [cache, setCache] = useState({});

  // Cache expiry time (1 hour)
  const CACHE_DURATION = 60 * 60 * 1000;

  // Load cached predictions on component mount
  useEffect(() => {
    const cachedData = localStorage.getItem('predictions_cache');
    if (cachedData) {
      try {
        const parsed = JSON.parse(cachedData);
        setCache(parsed);
      } catch (e) {
        console.error('Failed to parse cache:', e);
      }
    }
  }, []);

  // Load predictions when tab changes
  useEffect(() => {
    const gameType = activeTab.toUpperCase();
    const cached = cache[gameType];
    
    if (cached && (Date.now() - cached.timestamp < CACHE_DURATION)) {
      // Use cached data
      setPredictions(cached.data);
    } else {
      // Clear predictions when switching tabs if no valid cache
      setPredictions([]);
    }
  }, [activeTab, cache]);

  const handleGenerate = async () => {
    const gameType = activeTab.toUpperCase();
    
    // Check cache first
    const cached = cache[gameType];
    if (cached && (Date.now() - cached.timestamp < CACHE_DURATION)) {
      setPredictions(cached.data);
      return;
    }

    setLoading(true);
    setError(null);
    
    try {
      const data = await getPredictions(gameType);
      const newPredictions = data.predictions || [];
      setPredictions(newPredictions);
      
      // Update cache
      const newCache = {
        ...cache,
        [gameType]: {
          data: newPredictions,
          timestamp: Date.now()
        }
      };
      setCache(newCache);
      localStorage.setItem('predictions_cache', JSON.stringify(newCache));
    } catch (err) {
      console.error('Failed to fetch predictions:', err);
      setError(err.response?.data?.detail || err.message || 'Failed to fetch predictions');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen p-4 md:p-8" style={{backgroundColor: '#020617'}}>
      <div className="max-w-6xl mx-auto">
        
        {/* Header Section */}
        <div className="mb-8">
          <h1 className="text-4xl font-bold text-white mb-3">Predictive Analysis</h1>
          <p style={{color: '#cbd5e1'}}>
            AI-powered forecasts using Statistical, Machine Learning, and Deep Learning models.
          </p>
        </div>

        {/* Disclaimer Banner (Compliance Requirement) */}
        <div className="p-4 mb-8 rounded-lg" style={{background: 'rgba(251, 191, 36, 0.1)', border: '1px solid rgba(251, 191, 36, 0.3)', borderLeft: '4px solid #f59e0b'}}>
          <div className="flex items-start">
            <AlertTriangle className="h-5 w-5 mr-3 mt-0.5" style={{color: '#fbbf24'}} />
            <div>
              <h3 className="text-sm font-semibold" style={{color: '#fbbf24'}}>Educational Purpose Only</h3>
              <p className="text-sm mt-1" style={{color: '#cbd5e1'}}>
                These predictions are generated by experimental algorithms. Lottery draws are stochastic processes; 
                past performance does not guarantee future results. Do not use for gambling.
              </p>
            </div>
          </div>
        </div>

        {/* Controls */}
        <div className="flex flex-col sm:flex-row justify-between items-center mb-8 gap-4">
          {/* Game Toggle */}
          <div className="p-1 rounded-lg flex" style={{background: '#0f172a', border: '1px solid #1e293b'}}>
            <button
              onClick={() => setActiveTab('4d')}
              className="px-6 py-2 rounded-md text-sm font-medium transition-all"
              style={{
                background: activeTab === '4d' ? 'rgba(59, 130, 246, 0.15)' : 'transparent',
                color: activeTab === '4d' ? '#60a5fa' : '#94a3b8',
                border: activeTab === '4d' ? '1px solid rgba(59, 130, 246, 0.3)' : '1px solid transparent'
              }}
              onMouseEnter={(e) => {
                if (activeTab !== '4d') {
                  e.target.style.color = '#cbd5e1';
                }
              }}
              onMouseLeave={(e) => {
                if (activeTab !== '4d') {
                  e.target.style.color = '#94a3b8';
                }
              }}
            >
              4D
            </button>
            <button
              onClick={() => setActiveTab('toto')}
              className="px-6 py-2 rounded-md text-sm font-medium transition-all"
              style={{
                background: activeTab === 'toto' ? 'rgba(124, 58, 237, 0.15)' : 'transparent',
                color: activeTab === 'toto' ? '#a78bfa' : '#94a3b8',
                border: activeTab === 'toto' ? '1px solid rgba(124, 58, 237, 0.3)' : '1px solid transparent'
              }}
              onMouseEnter={(e) => {
                if (activeTab !== 'toto') {
                  e.target.style.color = '#cbd5e1';
                }
              }}
              onMouseLeave={(e) => {
                if (activeTab !== 'toto') {
                  e.target.style.color = '#94a3b8';
                }
              }}
            >
              TOTO
            </button>
          </div>

          {/* Action Button */}
          <button
            onClick={handleGenerate}
            disabled={loading}
            className="flex items-center px-6 py-3 rounded-lg font-semibold text-white transition-all"
            style={{
              background: loading ? '#64748b' : '#7c3aed',
              cursor: loading ? 'not-allowed' : 'pointer',
              boxShadow: loading ? 'none' : '0 0 20px rgba(124, 58, 237, 0.3)'
            }}
            onMouseEnter={(e) => {
              if (!loading) {
                e.target.style.background = '#6d28d9';
                e.target.style.boxShadow = '0 0 30px rgba(124, 58, 237, 0.5)';
              }
            }}
            onMouseLeave={(e) => {
              if (!loading) {
                e.target.style.background = '#7c3aed';
                e.target.style.boxShadow = '0 0 20px rgba(124, 58, 237, 0.3)';
              }
            }}
          >
            {loading ? 'Running Models...' : `Generate ${activeTab.toUpperCase()} Forecast`}
          </button>
        </div>

        {/* Error Display */}
        {error && (
          <div className="mb-6 p-4 rounded-lg" style={{background: 'rgba(239, 68, 68, 0.1)', border: '1px solid rgba(239, 68, 68, 0.4)'}}>
            <p style={{color: '#fca5a5'}}>{error}</p>
          </div>
        )}

        {/* Grid Layout for Cards */}
        {predictions.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {predictions.map((pred, index) => (
              <PredictionCard
                key={index}
                type={activeTab}
                modelName={pred.model_name}
                numbers={pred.predicted_numbers}
                confidence={pred.confidence_score}
                rationale={pred.rationale}
              />
            ))}
          </div>
        ) : (
          /* Empty State */
          <div className="text-center py-20 rounded-xl border border-dashed" style={{background: '#0f172a', borderColor: '#334155'}}>
            <div className="mx-auto h-12 w-12 mb-4" style={{color: '#64748b'}}>
              <BarChart2 className="w-full h-full" />
            </div>
            <h3 className="text-lg font-medium text-white">No predictions yet</h3>
            <p className="mt-1" style={{color: '#94a3b8'}}>Select a game and click generate to run the AI models.</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default PredictionsPage;